version: '3.8'

services:
  backend:
    build: #builds the docker image locally
      context: ./server
      dockerfile: Dockerfile
    # env_file:
    #   - ./server/.env #load external env file
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=test
      - MONGODB_URL=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - frontendURL=${frontendURL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: npm run test


  frontend:
    depends_on:
      - backend
    build: #builds the docker image locally
      context: ./client
      dockerfile: Dockerfile
#    env_file:
#      - ./client/.env #load external env file
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=test
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

