apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-server
  template:
    metadata:
      labels:
        app: nodejs-server
    spec:
      containers:
      - name: nodejs-server
        image: aj09/finance-node #dockerhub
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:   #env variable
        - name: MONGODB_URL
          valueFrom: 
            secretKeyRef: 
              name: secret # secret metadata name
              key:  MONGODB_URL
        - name: JWT_SECRET
          valueFrom: 
            secretKeyRef: 
              name: secret # secret metadata name
              key: JWT_SECRET
        - name: OPENAI_API_KEY
          valueFrom: 
            secretKeyRef: 
              name: secret # secret metadata name
              key: OPENAI_API_KEY 
        - name: frontendURL
          valueFrom:
            configMapKeyRef: 
              name: config # configMap file
              key: frontendUrl

---
#service
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: ClusterIP
  selector:
    app: nodejs-server
  ports:
  - port: 5000
    targetPort: 5000
    # nodePort: 31000



    

