apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-server
  template:
    metadata:
      labels:
        app: nodejs-server
    spec:
      containers:
      - name: nodejs-server
        image: aj09/finance-node #dockerhub
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:   #env variable
        - name: MONGODB_URL
          valueFrom: 
            secretKeyRef: 
              name: secret # secret metadata name
              key:  MONGODB_URL
        - name: JWT_SECRET
          valueFrom: 
            secretKeyRef: 
              name: secret # secret metadata name
              key: JWT_SECRET
        - name: OPENAI_API_KEY
          valueFrom: 
            secretKeyRef: 
              name: secret # secret metadata name
              key: OPENAI_API_KEY                   

---
#service
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-server
  ports:
  - port: 3000
    targetPort: 3000
    

